//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winformstut.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Threading;
    using System.Threading.Tasks;

    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
        public async Task<int> CustomeSaveAsync()
        {
            try
            {
                int tInt = await this.SaveChangesAsync();
                return tInt;
            }
            catch (Exception ex)
            {
                return 0;
            }
        }
        //public override Task<int> SaveChangesAsync()
        //{
        //    try
        //    {
        //        return CustomeSaveAsync();
        //    }
        //    catch (Exception ex)
        //    {
        //        return Task.FromResult(1);
        //    }
        //}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
